---
title: "An Exploratory Analysis of Police Acquisition of Militarized Equipment"
output:
  html_notebook: default
  html_document: default
---


## Setup
Load libraries and import the police acquisitions data set.
```{r, results='hide'}
library(data.table)
library(ggplot2)
library(scales)
library(ggmap)
library(statebins)
library(plyr)
library(readxl)
library(stringr)
library(stringi)
library(extrafont)
library(USA.county.data)
library(lattice)
#library(devtools)
#devtools::install_github("deleetdk/USA.county.data") # only need to load this once

data = fread("~/projects/policeMilitarySurplus/data/policeAcquisitionOfMilitarySurplus2014.csv")
colnames(data) = make.names(names(data)) # make column names R-friendly (remove spaces)
data$Item.Name = sapply(data$Item.Name, trimws) # trim whitespace
data = data[!(data$Item.Name == ""), ] # get rid of empty string value
```

Dataset format:
```{r, echo=TRUE}
head(data, n=1)
```
NSN stands for NATO Stock Number, it's a unique identifier for military supplies across NATO nations


## Which items were purchased the most?
```{r}
itemFreq = count(data, "Item.Name")
itemFreq = itemFreq[with(itemFreq, order(-freq)), ]
head(itemFreq, n=10)
```


